server:
  port: 8100
  
eureka:
  client:
    serviceUrl:
#      defaultZone: http://127.0.0.1:8760/eureka/,http://127.0.0.1:8761/eureka/
      defaultZone: http://127.0.0.1:8760/eureka/
#      defaultZone: http://172.18.8.22:1111/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    
spring:
  application:
    name: zipkin-server
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zipkin
    username: root
    password: root
    
zipkin:
  storage:
    type: mysql
