server:
  port: 8761

spring:
  application:
    name: eureka-server1
    
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8760/eureka/ 