server:
  port: 8772


eureka:
  client:
    serviceUrl:
#      defaultZone: http://127.0.0.1:8760/eureka/,http://127.0.0.1:8761/eureka/
      defaultZone: http://127.0.0.1:8760/eureka/
      
spring:
  application:
    name: hello-service